ci test

diff --git a/.github/workflows/clang-format.yml b/.github/workflows/clang-format.yml
--- a/.github/workflows/clang-format.yml
+++ b/.github/workflows/clang-format.yml
@@ -1,19 +1,24 @@
-name: Clang Format
+name: cpp-linter
 
-on:
+on: 
   push:
     branches:
       - master
 
 jobs:
-  deploy:
+  cpp-linter:
     runs-on: ubuntu-latest
     steps:
-      - name: format1
-        run: pwd
-      - name: format2
-        run: ls -la
-      - name: format123
-        run: ls -la ..
-      - name: format3
-        run: clang-format --style=llvm --sort-includes Source/**/*.cpp Source/**/*.hpp --Werror -i
+      - uses: actions/checkout@v3
+      - uses: cpp-linter/cpp-linter-action@v2
+        id: linter
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          style: llvm
+
+      - name: Fail fast?!
+        if: steps.linter.outputs.checks-failed > 0
+        run: echo "Some files failed the linting checks!"
+        # for actual deployment
+        # run: exit 1
